// Real file/folder icons (Material Icon Theme, MIT), resolved at runtime. The
// mapping + SVGs live in `public/file-icons/` (generated by scripts/gen-file-icons.mjs),
// served statically — so they cost nothing at startup and load on demand when the
// editor first opens. Until the map is loaded (or for an unmatched name), the tree
// falls back to its generic folder/file glyph.

import { create } from "zustand";
import { baseName } from "./language";

export interface IconMap {
  fileNames: Record<string, string>;
  fileExtensions: Record<string, string>;
  folderNames: Record<string, string>;
  folderNamesExpanded: Record<string, string>;
  defaults: { file: string | null; folder: string | null; folderOpen: string | null };
}

interface IconState {
  map: IconMap | null;
  /** Fetch the icon map once (idempotent). Failure is logged, not thrown. */
  load: () => void;
}

let started = false;

export const useFileIconStore = create<IconState>((set) => ({
  map: null,
  load: () => {
    if (started) return;
    started = true;
    fetch("/file-icons/icons.json")
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`))))
      .then((m: IconMap) => set({ map: m }))
      .catch((e) => console.error("[file-icons] failed to load icon map:", e));
  },
}));

/** Subscribe to the loaded icon map (null until it arrives). */
export const useFileIcons = (): IconMap | null => useFileIconStore((s) => s.map);

const url = (svg: string | null | undefined): string | null => (svg ? `/file-icons/${svg}` : null);

/**
 * Icon URL for a file, by exact name then by longest matching extension (so
 * `Component.test.tsx` prefers a `test.tsx` icon over `tsx`). Falls back to the
 * default file icon. Returns null only if the map has no default.
 */
export function fileIconUrl(map: IconMap, path: string): string | null {
  const name = baseName(path).toLowerCase();
  const byName = map.fileNames[name];
  if (byName) return url(byName);
  const parts = name.split(".");
  for (let i = 1; i < parts.length; i++) {
    const ext = parts.slice(i).join(".");
    const byExt = map.fileExtensions[ext];
    if (byExt) return url(byExt);
  }
  return url(map.defaults.file);
}

/** Icon URL for a folder, by name (open/closed variant), else the default folder. */
export function folderIconUrl(map: IconMap, path: string, open: boolean): string | null {
  const name = baseName(path).toLowerCase();
  const table = open ? map.folderNamesExpanded : map.folderNames;
  const byName = table[name];
  if (byName) return url(byName);
  return url(open ? map.defaults.folderOpen : map.defaults.folder);
}
