// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async ping(msg: string) : Promise<Pong> {
    return await TAURI_INVOKE("ping", { msg });
},
/**
 * Start a new `claude` session rooted at `repo_path`, applying this conversation's
 * controls (model / effort / permission mode / ultracode) at spawn so the live
 * stream starts in EXACTLY the state the UI shows — never the old hardcoded
 * defaults. Returns our session id; conversation/state/permission events are
 * emitted on the Tauri event bus.
 */
async spawnSession(repoPath: string, resume: string | null, model: string | null, effort: string | null, permissionMode: string | null, ultracode: boolean) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spawn_session", { repoPath, resume, model, effort, permissionMode, ultracode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch the slash commands available in `cwd` WITHOUT starting a persistent
 * session. Spawns a short-lived `claude`, performs the `initialize` handshake
 * (spec §4.4), reads the advertised commands from its `control_response`, and
 * tears the process down. This lets the composer populate its `/` autocomplete
 * before the lazy session spawn — so typing `/pickup` as the very first thing
 * works — without leaving a process alive. Returns an empty list if the
 * handshake does not complete within the deadline (the live session, spawned on
 * the first message, will still emit commands later via `SessionCommandsEvent`).
 */
async fetchSlashCommands(cwd: string) : Promise<Result<SlashCommand[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_slash_commands", { cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rebuild a resumed conversation's history from Claude's on-disk transcript.
 * 
 * `claude --resume` does not re-stream past messages, so the live event path
 * delivers nothing for an existing conversation. The UI calls this after
 * re-spawning a session to replay its history into the store. An absent
 * transcript yields an empty list (not an error). File IO runs off the async
 * runtime via `spawn_blocking` so a large transcript never stalls it.
 */
async loadSessionHistory(sessionId: string) : Promise<Result<ConversationItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_session_history", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a resumed conversation's current context fill (used tokens + window) from
 * its on-disk transcript, so the UI can show the context ring as soon as the
 * conversation is opened / its stream turned on — before the first new turn streams
 * live usage. An absent transcript yields all-`None` (not an error). File IO runs
 * off the async runtime via `spawn_blocking`.
 */
async loadSessionContext(sessionId: string) : Promise<Result<ContextFill, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_session_context", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load a sub-agent's (`Agent` tool, or a workflow agent) full transcript,
 * normalized into the same items the live conversation renders. Empty if absent.
 */
async loadSubagentTranscript(sessionId: string, agentId: string) : Promise<Result<ConversationItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_subagent_transcript", { sessionId, agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load a workflow run's manifest (`workflows/<run_id>.json`). `null` if absent.
 */
async loadWorkflowRun(sessionId: string, runId: string) : Promise<Result<WorkflowRun | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_workflow_run", { sessionId, runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a background task's output from the ABSOLUTE path the CLI reported
 * (`BackgroundTask.output_file`). The CLI writes Bash-bg / Monitor output to a temp dir
 * the app can't reconstruct, so the live tail reads this path directly. `null` if
 * absent. One-shot read — the display task layers the polling on top. The reader guards
 * the path (must be a `…/tasks/*.output` file) against an arbitrary-file read.
 */
async readTaskOutputFile(path: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_task_output_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch the real subscription usage percentages (5h + weekly windows). The stream
 * only carries a coarse rate-limit status, so this replicates the CLI's internal
 * `GET /api/oauth/usage` (OAuth token read from `~/.claude/.credentials.json` then
 * the macOS Keychain). Read-only — never refreshes/writes the token. Account-global
 * (not per-session); on error the UI degrades to the coarse `rate_limit` status. The
 * endpoint is itself rate-limited, so the caller throttles (poll + on-open + manual).
 * Errors are typed ([`UsageError`]) so the UI can show a tailored next step.
 */
async getPlanUsage() : Promise<Result<PlanUsage, UsageError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_plan_usage") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a user turn to a session.
 */
async sendMessage(session: string, text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_message", { session, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Answer a pending `can_use_tool` permission prompt (allow / deny).
 */
async answerPermission(session: string, requestId: string, decision: PermissionDecision) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("answer_permission", { session, requestId, decision }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Switch the session's permission mode at runtime.
 */
async setPermissionMode(session: string, mode: PermissionMode) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_permission_mode", { session, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Switch the session's active model at runtime (`set_model`).
 */
async setModel(session: string, model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_model", { session, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the session's reasoning effort level at runtime (`apply_flag_settings`).
 * Rejects an invalid level BEFORE sending: the CLI silently swallows anything
 * outside low/medium/high/xhigh/max, so an unvalidated value would no-op without
 * any error — exactly the silent failure we must avoid. (Per-model gating — e.g.
 * `max`/`xhigh` not on every model — is the front-end gauge's job; this guard only
 * rejects values the wire never accepts.)
 */
async setEffortLevel(session: string, level: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_effort_level", { session, level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enable "ultracode" (xhigh effort + standing dynamic-workflow orchestration) at
 * runtime. Disabling is done by selecting any plain effort level via
 * [`set_effort_level`], which clears the flag.
 */
async setUltracode(session: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_ultracode", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ask the binary to generate a short conversation title from `description` (the
 * user's accumulated messages so far), like the official VS Code extension. `seq` is
 * a monotonic per-conversation tag echoed back in the `SessionTitleEvent` so the
 * front can drop an out-of-order (stale) response. Fire-and-forget: the title comes
 * back asynchronously as a `SessionTitleEvent`, which the front applies as the
 * conversation name (unless the user set a custom title meanwhile). A generation
 * failure is swallowed in the core — the front keeps its placeholder / last title.
 */
async generateConversationTitle(session: string, description: string, seq: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_conversation_title", { session, description, seq }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Interrupt the current turn (without killing the process).
 */
async interruptSession(session: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("interrupt_session", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Query a running session's LIVE MCP server status (real connection state +
 * tools per server) via the `mcp_status` control request — the authoritative
 * source the conversation view uses (NOT the stale `system/init` snapshot).
 * Errors with "unknown session" when the conversation has no live `claude`
 * process; the UI then falls back to the configured view.
 */
async mcpStatus(session: string) : Promise<Result<McpServerLive[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mcp_status", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enable/disable a live MCP server in a running session (`mcp_toggle`). Optimistic
 * — returns once sent; the UI re-polls `mcp_status` to reflect the new state, and a
 * CLI rejection surfaces as a timeline control error.
 */
async mcpToggle(session: string, serverName: string, enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mcp_toggle", { session, serverName, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reconnect a live MCP server (`mcp_reconnect`) — after a failure or once auth is
 * granted. Optimistic; the UI re-polls `mcp_status`.
 */
async mcpReconnect(session: string, serverName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mcp_reconnect", { session, serverName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Forget a live MCP server's stored OAuth credentials (`mcp_clear_auth`).
 */
async mcpClearAuth(session: string, serverName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mcp_clear_auth", { session, serverName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start the OAuth flow for a live MCP server (`mcp_authenticate`). Returns the
 * `authUrl` to open in the browser (the front opens it) and whether the user must
 * finish a manual callback. Errors with "unknown session" when there's no live
 * process.
 */
async mcpAuthenticate(session: string, serverName: string) : Promise<Result<McpAuthResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mcp_authenticate", { session, serverName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tear a session down and remove it from the registry.
 */
async stopSession(session: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_session", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop ONE background task (a `run_in_background` Bash / Monitor / sub-agent) by its
 * `task_id`, without ending the turn or the session. Sends a `stop_task` control
 * request; the task then settles to `stopped` via its normal `task_*` lifecycle
 * (surfaced to the UI through `session_task`). No-op if the session is no longer live.
 */
async stopTask(session: string, taskId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_task", { session, taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open the OS terminal on this conversation: resume it as an interactive
 * `claude` session (`claude --resume <session_id>`) in its working directory.
 * 
 * This launches a *separate*, user-driven `claude` outside the app — the same
 * session id the supervisor drives, resumed from Claude's on-disk transcript
 * (not the live stream). macOS only for now (drives Terminal.app via
 * AppleScript); other platforms return an error the UI can surface. The
 * blocking `osascript` call runs off the async runtime via `spawn_blocking`.
 */
async openInTerminal(cwd: string, sessionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_in_terminal", { cwd, sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Bounce the app's Dock icon (macOS) / flash the taskbar (other platforms) to
 * get the user's attention when an agent finishes or needs input while the app
 * is in the background. `critical` bounces repeatedly until the app is focused
 * (a permission/question is waiting); otherwise it bounces once (a turn ended).
 * The OS clears the request automatically when the window regains focus, so the
 * front never has to cancel it. A no-op if the main window is gone.
 */
async requestUserAttention(critical: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_user_attention", { critical }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List every worktree of the repository `repo_path` lives in (main first).
 */
async listWorktrees(repoPath: string) : Promise<Result<WorktreeInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_worktrees", { repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Working-tree status of one worktree (dirty / untracked / ahead-behind).
 */
async worktreeStatus(worktreePath: string) : Promise<Result<WorktreeStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("worktree_status", { worktreePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a worktree for `branch` (new branch off `base_ref` when `new_branch`,
 * else an existing branch). Returns the created worktree's info.
 */
async createWorktree(repoPath: string, branch: string, baseRef: string | null, newBranch: boolean) : Promise<Result<WorktreeInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_worktree", { repoPath, branch, baseRef, newBranch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a worktree. `git` refuses a dirty or main worktree unless `force`,
 * which the UI only passes after an explicit, separate confirmation.
 */
async removeWorktree(repoPath: string, worktreePath: string, force: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_worktree", { repoPath, worktreePath, force }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the configured extensions visible to the repository (or worktree) at
 * `repo_path`: MCP servers (+ enabled state), plugins, skills, sub-agents,
 * each tagged with its scope. Best-effort — never errors on missing config; the
 * blocking file IO runs off the async runtime.
 */
async listExtensions(repoPath: string) : Promise<Result<ExtensionsSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_extensions", { repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enable or disable a plugin (by id `<plugin>@<marketplace>`) in the user's
 * `~/.claude/settings.json`. USER-GLOBAL toggle (not per-repo); takes effect on
 * the next (re)start of a conversation. The write is atomic and preserves every
 * other key. The blocking file IO runs off the async runtime.
 */
async setPluginEnabled(pluginId: string, enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_plugin_enabled", { pluginId, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Everything a single plugin provides (skills / sub-agents / MCP servers) for the
 * per-plugin explorer — scanned regardless of the plugin's enabled state so a
 * disabled plugin stays browsable. `repo_path` selects the install relevant to the
 * repo. Best-effort; the blocking file IO runs off the async runtime.
 */
async listPluginContents(repoPath: string, pluginId: string) : Promise<Result<PluginContents, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_plugin_contents", { repoPath, pluginId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether a filesystem path currently exists. Used to detect a conversation
 * whose worktree cwd was removed, so the UI can fall back to the repo's main
 * checkout instead of failing to spawn `claude` in a directory that is gone.
 */
async pathExists(path: string) : Promise<boolean> {
    return await TAURI_INVOKE("path_exists", { path });
},
/**
 * Working-tree status: current branch, ahead/behind, and changed files.
 */
async gitStatus(cwd: string) : Promise<Result<GitStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_status", { cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Diff of one working-tree file against HEAD (old = HEAD, new = on-disk),
 * for the source-control view's diff editor.
 */
async gitDiff(cwd: string, path: string, origPath: string | null) : Promise<Result<GitDiff, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_diff", { cwd, path, origPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A page of commit history across all refs (for the graph / git tree).
 */
async gitLog(cwd: string, limit: number, skip: number) : Promise<Result<CommitInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_log", { cwd, limit, skip }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Local + remote-tracking branches with their upstream tracking counts.
 */
async gitBranches(cwd: string) : Promise<Result<BranchInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_branches", { cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Files changed by a single commit (name-status vs its first parent).
 */
async gitCommitFiles(cwd: string, oid: string) : Promise<Result<CommitFile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_commit_files", { cwd, oid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Diff of one file introduced by a commit (old = parent, new = commit).
 */
async gitCommitFileDiff(cwd: string, oid: string, path: string, origPath: string | null) : Promise<Result<GitDiff, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_commit_file_diff", { cwd, oid, path, origPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stage all changes and commit them with `message`. Returns the new short oid.
 */
async gitCommit(cwd: string, message: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_commit", { cwd, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Push the current branch to its upstream.
 */
async gitPush(cwd: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_push", { cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pull the current branch (`--ff-only`).
 */
async gitPull(cwd: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_pull", { cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch all remotes (with prune).
 */
async gitFetch(cwd: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_fetch", { cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List one directory level (dirs first, then files, alpha) for the file tree.
 */
async readDir(path: string) : Promise<Result<FsEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_dir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a file into the editor (guards binary / oversize — see `fs::read_file`).
 */
async readFile(path: string) : Promise<Result<FileContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read an image file for the viewer, base64-encoded (see `fs::read_image`). The
 * front renders it as a `data:` URL instead of routing the file to Monaco.
 */
async readImage(path: string) : Promise<Result<ImageContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_image", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write the editor buffer back to disk (save).
 */
async writeFile(path: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_file", { path, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start (or replace) the live watch on `path` — the editor's current working
 * directory. Changes under it arrive as a debounced `FsChangeEvent`.
 */
async watchDir(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("watch_dir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the live filesystem watch (editor panel closed / no conversation shown).
 */
async unwatchDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unwatch_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create an empty file at `path` (explorer "New File"). Errors if the name exists.
 */
async createFile(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new directory at `path` (explorer "New Folder"). Errors if it exists.
 */
async createDir(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_dir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename / move `from` to `to` (explorer "Rename", and the move half of cut +
 * paste). Refuses to overwrite an existing destination.
 */
async renameEntry(from: string, to: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_entry", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Recursively copy `from` to `to` (the copy half of copy + paste). Refuses to
 * overwrite an existing destination; the front resolves a non-colliding name.
 */
async copyEntry(from: string, to: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_entry", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Move `path` to the OS trash (explorer "Delete" — recoverable from the Finder),
 * never an irreversible unlink.
 */
async deleteToTrash(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_to_trash", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reveal `path` in the OS file manager (macOS Finder), selecting the item — the
 * explorer's "Reveal in Finder". Forwards to the opener plugin's native reveal.
 */
async revealInFinder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_in_finder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open (or replace) the integrated terminal `id`: spawn the user's login shell
 * under a PTY rooted at `cwd`, sized `cols`×`rows`. Output streams as
 * `TerminalOutputEvent`; the shell exiting fires `TerminalExitEvent`.
 */
async terminalOpen(id: string, cwd: string, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_open", { id, cwd, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Feed keystrokes / pasted text to a terminal's shell.
 */
async terminalWrite(id: string, data: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_write", { id, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Report a terminal's new grid size (xterm fitted to the panel).
 */
async terminalResize(id: string, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_resize", { id, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Kill a terminal's shell and forget it.
 */
async terminalClose(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_close", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load the persisted repos + conversations + active selection (UI hydration at boot).
 */
async loadPersistedState() : Promise<Result<PersistedState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_persisted_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Insert or update a repo (idempotent by id).
 */
async upsertRepo(repo: RepoRecord) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_repo", { repo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a repo; its conversations cascade away.
 */
async deleteRepo(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_repo", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Insert or update a conversation's metadata (idempotent by stable id).
 */
async upsertConversation(conversation: ConversationRecord) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_conversation", { conversation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Forget a conversation's metadata.
 */
async deleteConversation(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_conversation", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist (or clear, with `null`) the active conversation's stable id.
 */
async setActiveConversation(id: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_conversation", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drop ALL persisted data (dev escape hatch + Settings "drop all"). Claude's
 * on-disk transcripts are untouched.
 */
async wipeAllData() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wipe_all_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
fsChangeEvent: FsChangeEvent,
fsWatchErrorEvent: FsWatchErrorEvent,
sessionCommandsEvent: SessionCommandsEvent,
sessionMessageEvent: SessionMessageEvent,
sessionPermissionEvent: SessionPermissionEvent,
sessionStateEvent: SessionStateEvent,
sessionTaskEvent: SessionTaskEvent,
sessionTitleEvent: SessionTitleEvent,
terminalExitEvent: TerminalExitEvent,
terminalOutputEvent: TerminalOutputEvent,
tickEvent: TickEvent
}>({
fsChangeEvent: "fs-change-event",
fsWatchErrorEvent: "fs-watch-error-event",
sessionCommandsEvent: "session-commands-event",
sessionMessageEvent: "session-message-event",
sessionPermissionEvent: "session-permission-event",
sessionStateEvent: "session-state-event",
sessionTaskEvent: "session-task-event",
sessionTitleEvent: "session-title-event",
terminalExitEvent: "terminal-exit-event",
terminalOutputEvent: "terminal-output-event",
tickEvent: "tick-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * One sub-agent available to a repository (file-based or plugin-provided).
 */
export type AgentInfo = { name: string; description: string | null; model: string | null; scope: ExtScope; source: string | null; 
/**
 * Absolute path to the agent's `.md` definition — the UI reads it to render a
 * clean markdown view of the sub-agent.
 */
path: string }
/**
 * A normalized background task, keyed by `task_id` and updated in place as its
 * `task_*` lifecycle events arrive. The single model behind the (future) sub-agent /
 * workflow / Monitor / background-Bash views — the rich per-producer detail (full
 * transcript, manifest, output) is read from disk on demand (see
 * [`super::subagents`]), never carried here.
 */
export type BackgroundTask = { 
/**
 * Stable id that ties every `task_*` event of this task together.
 */
task_id: string; kind: BackgroundTaskKind; 
/**
 * The `tool_use` block that spawned the task (== `parent_tool_use_id` of any
 * streamed child content). Lets the UI anchor the task under its tool card.
 */
tool_use_id: string | null; 
/**
 * Human label = the NAME the agent gave the task (the tool's `description`, e.g.
 * "build the app"). This is the meaningful, readable line shown pinned in the UI.
 * `None` when the agent gave no description (the UI then falls back to `command`).
 */
label: string | null; 
/**
 * The raw shell command of a `Bash` task (captured from the tool_use input). Shown
 * IN ADDITION to `label` in the output popover (the name says what, the command
 * says how), and used as the pinned-line fallback when there is no `label`. `None`
 * for non-Bash tasks.
 */
command: string | null; 
/**
 * Sub-agent type (`Agent` only, e.g. `"Explore"`).
 */
subagent_type: string | null; 
/**
 * Model the sub-agent ran on (`Agent` only), e.g. `"claude-haiku-4-5"`. Captured
 * from the sub-agent's streamed `assistant` message (`message.model`) — the wire's
 * ONLY place a sub-agent's model surfaces (it is absent from every `task_*` event
 * and from the normalized transcript). `None` for non-agent tasks, or until the
 * sub-agent streams its first assistant message.
 */
model: string | null; 
/**
 * The sub-agent's id (`Agent` only), i.e. the key for [`super::subagents::load_subagent_transcript`].
 * Derived from the `output_file` basename (`subagents/agent-<agentId>.jsonl`), since
 * the wire carries it only inside that path. Lets the UI drill into the transcript
 * without re-parsing the path itself.
 */
agent_id: string | null; status: BackgroundTaskStatus; 
/**
 * Latest live progress text (`Workflow`: `"<phase>: <label>"`).
 */
progress: string | null; 
/**
 * Total tokens used (from the `task_notification` usage roll-up).
 */
tokens: number | null; 
/**
 * Tool-call count (from the usage roll-up).
 */
tool_uses: number | null; 
/**
 * Wall-clock duration in ms (from the usage roll-up).
 */
duration_ms: number | null; 
/**
 * End-of-task human summary (from the `task_notification`).
 */
summary: string | null; 
/**
 * ABSOLUTE on-disk path holding the task's full output. The CLI writes a Bash-bg /
 * Monitor output to a TEMP dir (`/tmp/claude-<uid>/<slug>/<session>/tasks/<id>.output`),
 * NOT under the session dir — so this path (taken verbatim from the wire: the Bash
 * tool_result at start, then `task_notification.output_file`) is the ONLY reliable
 * way to read it back. For an `Agent` it is the sub-agent transcript path.
 */
output_file: string | null }
/**
 * Which producer a background task came from. The `claude` binary runs ONE generic
 * background-task system for four producers; we tell them apart from `task_type`
 * plus the correlated `tool_use` name (see [`super::assembler`]).
 */
export type BackgroundTaskKind = 
/**
 * A sub-agent launched by the `Agent` tool (`task_type:"local_agent"`).
 */
"agent" | 
/**
 * A dynamic-workflow run launched by the `Workflow` tool.
 */
"workflow" | 
/**
 * A shell command launched by `Bash` with `run_in_background:true`.
 */
"bash" | 
/**
 * A live watch launched by the `Monitor` tool.
 */
"monitor" | 
/**
 * A background task whose producer could not be classified yet.
 */
"other"
/**
 * Coarse lifecycle status of a background task, normalized from `task_*` events.
 */
export type BackgroundTaskStatus = 
/**
 * Created and not yet finished (`task_started`, or a non-terminal patch).
 */
"running" | 
/**
 * Finished successfully (`patch.status`/notification `"completed"`).
 */
"completed" | 
/**
 * Finished with an error (`"failed"`/`"error"`).
 */
"failed" | 
/**
 * Cancelled via `TaskStop` / session end (`"stopped"`/`"cancelled"`).
 */
"stopped"
/**
 * One branch ref. `is_remote` distinguishes `refs/remotes/*` from local
 * `refs/heads/*`; `ahead`/`behind` come from the branch's upstream tracking
 * (`None` when it has no upstream).
 */
export type BranchInfo = { 
/**
 * Short name, e.g. `main` or `origin/feature`.
 */
name: string; 
/**
 * Commit oid the branch points at.
 */
oid: string; 
/**
 * The currently checked-out branch.
 */
is_head: boolean; 
/**
 * A remote-tracking branch (`refs/remotes/*`).
 */
is_remote: boolean; 
/**
 * Upstream short name; `None` when unset.
 */
upstream: string | null; 
/**
 * Commits ahead of upstream.
 */
ahead: number | null; 
/**
 * Commits behind upstream.
 */
behind: number | null }
/**
 * One file changed by a commit (name-status against its first parent).
 */
export type CommitFile = { path: string; 
/**
 * Source path for a rename/copy; `None` otherwise.
 */
orig_path: string | null; 
/**
 * Status letter: `M A D R C T`.
 */
status: string }
/**
 * One commit in the history. `parents` are full oids (0 = root, 1 = normal,
 * 2+ = merge), which the front uses to draw the graph. `refs` are the branch/tag
 * names pointing at this commit (decoration), for badges.
 */
export type CommitInfo = { 
/**
 * Full commit oid.
 */
oid: string; 
/**
 * Abbreviated oid (as git chooses it).
 */
short_oid: string; 
/**
 * Parent commit oids, in git's order.
 */
parents: string[]; author_name: string; author_email: string; 
/**
 * Author timestamp, Unix seconds.
 */
timestamp: number; 
/**
 * First line of the commit message.
 */
subject: string; 
/**
 * Ref names pointing here (branches/tags/`HEAD`), already de-decorated.
 */
refs: string[] }
/**
 * Context-meter seed for a conversation, read from its on-disk transcript so the
 * ring shows the real fill the moment a conversation is opened / its stream turned
 * on — before the first new turn streams live usage. `context_window` is the model's
 * provisional window (the transcript carries no authoritative `modelUsage`); the
 * first live `result` later refines it.
 */
export type ContextFill = { context_tokens: number | null; context_window: number | null }
/**
 * A normalized conversation event the UI applies incrementally. Tagged on
 * `kind` so the TS side is a simple discriminated union.
 */
export type ConversationItem = 
/**
 * An assistant turn began (from `stream_event/message_start`).
 */
{ kind: "message_started"; id: string; role: string; parent_tool_use_id: string | null } | 
/**
 * Live assistant text token(s) (from `content_block_delta/text_delta`).
 */
{ kind: "text_delta"; message_id: string | null; text: string } | 
/**
 * Live extended-thinking token(s).
 */
{ kind: "thinking_delta"; message_id: string | null; text: string } | 
/**
 * A past user turn, replayed from Claude's transcript when a conversation is
 * resumed. The live path never emits this — the UI adds user turns
 * optimistically on send — so it only appears during history restore.
 */
{ kind: "user_message"; id: string; text: string; parent_tool_use_id: string | null } | 
/**
 * The authoritative assembled assistant message (text + tool_use blocks).
 * Carries the same `id` as the streamed `message_start` — the UI reconciles.
 */
{ kind: "assistant_message"; id: string; blocks: NormalizedBlock[]; parent_tool_use_id: string | null } | 
/**
 * A tool result, delivered by the CLI as a `user` message.
 */
{ kind: "tool_result"; tool_use_id: string; content: JsonValue; is_error: boolean; parent_tool_use_id: string | null } | 
/**
 * End of a turn (`result`).
 */
{ kind: "turn_result"; subtype: string; is_error: boolean; result: JsonValue | null; api_error_status: string | null; total_cost_usd: number | null; num_turns: number | null; duration_ms: number | null } | 
/**
 * A non-conversational notice surfaced in the timeline. Two families:
 * - informational: `control_change` (a confirmed model/effort/mode move),
 * compact boundaries, …
 * - errors: `control_error`, `process_exited`, `send_failed`, `protocol_error`,
 * and the generic `error` — each carries `detail.message` (+ optional
 * `detail.detail`/`stderr`/`exit_code`) and renders as a visible error bubble.
 * This is the single channel any layer uses to surface an error without new
 * plumbing (the "zero silent error" contract).
 */
{ kind: "notice"; subtype: string; detail: JsonValue }
/**
 * A conversation's persisted metadata.
 * 
 * The stable `id` is the identity the whole app keys off. It is deliberately
 * distinct from the ephemeral live session handle (`session-N`), which is
 * in-memory only and never persisted — so other services can reference a
 * conversation by an id that survives restarts.
 */
export type ConversationRecord = { id: string; name: string; 
/**
 * FK to [`RepoRecord::id`].
 */
repo_id: string; 
/**
 * Absolute path the session was spawned in.
 */
cwd: string; 
/**
 * Unix ms timestamp the conversation was created.
 */
created_at: number; 
/**
 * Unix ms timestamp of the conversation's last activity — the last message
 * sent OR received. Drives the sidebar's most-recent-first ordering. Bumped
 * by the UI on each user send and turn result; pre-existing rows (created
 * before this column) are backfilled from the transcript mtime at boot (see
 * [`super::db::Store::backfill_last_activity`]).
 */
last_activity_at: number; 
/**
 * Claude's own session UUID (from system/init) — used for `--resume`.
 */
session_id: string | null; 
/**
 * Per-conversation controls, persisted so they survive a restart and are
 * re-applied at the next (lazy) spawn. While a session is LIVE its own state
 * (get_settings / system/init) is the source of truth; these hold the
 * last-known values to restore from. `None`/`false` fall back to the product
 * defaults at spawn (opus / xhigh / default).
 * 
 * `model` is the CLI alias chosen in the UI (e.g. "opus"); `effort` is one of
 * low/medium/high/xhigh; `ultracode` is the separate xhigh+orchestration tier;
 * `permission_mode` is one of the CLI modes (default/plan/acceptEdits/auto/…).
 */
model: string | null; effort: string | null; ultracode: boolean; permission_mode: string | null; 
/**
 * An unacknowledged, non-blocking status reminder to re-surface across
 * restarts: `"review"` (a turn finished and was never seen), `"error"` (the
 * last turn ended in error), or `"openQuestion"` (the heuristic flagged the
 * last turn as a question awaiting a reply). `None` once acknowledged ("Vu")
 * or superseded by the next message. Blocking states (a pending permission or
 * questionnaire) are deliberately NOT persisted — they only exist while the
 * process is live and must be answered in the thread. Mirrors the dismissable
 * part of the derived `AgentStatus` (see the front's `agent/status.ts`), the
 * single thing that, when off, can't be re-derived from the on-disk transcript.
 */
pending_reminder: string | null }
/**
 * Where a configuration entry originates. Drives the "by scope" grouping in the
 * UI. Serialized snake_case so the TS union is `"user" | "project" | …`.
 */
export type ExtScope = 
/**
 * Configured globally for the user (`~/.claude*`).
 */
"user" | 
/**
 * Shared by the repository (committed `.mcp.json` / `.claude/`), or the
 * project section of `~/.claude.json`.
 */
"project" | 
/**
 * Bound to this project but kept local (not shared) — `settings.local.json`
 * or a `local`-scoped plugin install.
 */
"local" | 
/**
 * Provided by an installed plugin.
 */
"plugin"
/**
 * The full configured picture for one repository, across all scopes.
 */
export type ExtensionsSnapshot = { mcp_servers: McpServerInfo[]; plugins: PluginInfo[]; skills: SkillInfo[]; agents: AgentInfo[]; 
/**
 * Config files that exist but could NOT be read/parsed (corrupt JSON, IO error).
 * The scan still degrades to a usable snapshot, but these are surfaced so a
 * broken config is never indiscernible from "nothing configured" — without them
 * a corrupt `~/.claude.json` reads as an empty inventory, and a corrupt
 * `settings.json` would (wrongly) show every plugin as enabled. Empty = clean.
 */
warnings: string[] }
/**
 * A file's contents plus the guards the editor needs: `too_large` (skipped, over
 * [`MAX_FILE_BYTES`]) and `binary` (a NUL byte was found — not shown as text).
 * In both guard cases `content` is empty.
 */
export type FileContent = { path: string; content: string; too_large: boolean; binary: boolean; size: number }
/**
 * Coalesced filesystem change notification for the editor panel: the (de-noised,
 * debounced) set of paths that changed under the watched working directory. The
 * UI reloads any open file in this set and refreshes any expanded tree dirs it
 * touches. Not session-keyed: there is a single active watch (the shown cwd).
 */
export type FsChangeEvent = { paths: string[] }
/**
 * One immediate child of a listed directory. The tree expands lazily (a click
 * reads exactly one level), so a huge repo never reads more than what is shown.
 */
export type FsEntry = { name: string; path: string; is_dir: boolean }
/**
 * The filesystem watcher backend hit an error and live updates may have stopped.
 * Surfaced so the editor panel can show a discreet "file watching interrupted"
 * hint instead of silently going stale. Not session-keyed (single active watch).
 */
export type FsWatchErrorEvent = { message: string }
/**
 * A file's contents on both sides of a diff, handed to the front's Monaco diff
 * editor (which computes the visual diff itself). An empty `old_text` means the
 * file was added; an empty `new_text` means it was deleted. When either side is
 * binary the texts are `None` and the front shows a "binary file" placeholder.
 */
export type GitDiff = { 
/**
 * Repo-relative path of the file being diffed.
 */
path: string; 
/**
 * "Before" side content. `None` when binary.
 */
old_text: string | null; 
/**
 * "After" side content. `None` when binary.
 */
new_text: string | null; 
/**
 * Either side looks binary — no text diff, the UI shows a placeholder.
 */
is_binary: boolean; 
/**
 * Human label for the "before" side (e.g. "HEAD", "a1b2c3d^").
 */
old_label: string; 
/**
 * Human label for the "after" side (e.g. "Working tree", "a1b2c3d").
 */
new_label: string }
/**
 * One changed path reported by `git status --porcelain=v2`. The `index_status` /
 * `worktree_status` are the two halves of git's `XY` code (`.` = unchanged).
 */
export type GitFileEntry = { 
/**
 * Path relative to the repository root (forward slashes, as git emits).
 */
path: string; 
/**
 * For a rename/copy, the path it came from; `None` otherwise.
 */
orig_path: string | null; 
/**
 * Index (staged) status letter: `M A D R C T .` or `?` (untracked).
 */
index_status: string; 
/**
 * Working-tree (unstaged) status letter, same alphabet.
 */
worktree_status: string; 
/**
 * Index differs from HEAD (there is something staged).
 */
staged: boolean; 
/**
 * Working tree differs from the index (there is something unstaged).
 */
unstaged: boolean; 
/**
 * Not yet tracked by git.
 */
untracked: boolean }
/**
 * Summary of `git status`: the current branch, its upstream tracking counts and
 * the changed files. Backs the source-control view's header + file list.
 */
export type GitStatus = { 
/**
 * Current branch name; `None` when detached.
 */
branch: string | null; 
/**
 * Full HEAD commit oid; `None` on an unborn branch.
 */
head: string | null; 
/**
 * Upstream ref short name (e.g. `origin/main`); `None` when unset.
 */
upstream: string | null; 
/**
 * Commits ahead of upstream.
 */
ahead: number; 
/**
 * Commits behind upstream.
 */
behind: number; 
/**
 * The branch has no commits yet (unborn HEAD).
 */
unborn: boolean; 
/**
 * Changed entries (staged + unstaged + untracked), in git's order.
 */
files: GitFileEntry[] }
/**
 * An image file's bytes, base64-encoded for the webview to render as a `data:`
 * URL. Unlike [`read_file`], the binary content IS the payload here — images are
 * never decoded as text. `too_large` (over [`MAX_FILE_BYTES`]) leaves
 * `data_base64` empty; the front shows a guard instead of the image.
 */
export type ImageContent = { path: string; 
/**
 * Base64 of the raw file bytes, NO `data:` prefix (the front prepends the
 * `data:<mime>;base64,` header, choosing the MIME from the extension).
 */
data_base64: string; too_large: boolean; size: number }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Result of an `mcp_authenticate` control request (OAuth start for an http/sse
 * server). The binary returns an `authUrl` to open in the browser; the loopback
 * redirect is handled by the CLI itself in the common case. `requires_user_action`
 * is true when the flow needs the user to paste back a callback URL (the rarer
 * non-loopback path — surfaced to the UI). `error` carries a rejection message
 * (auth not supported, server unknown, …) without it being a fatal session error.
 */
export type McpAuthResult = { auth_url: string | null; requires_user_action: boolean; error: string | null }
/**
 * One MCP server visible to a repository, with its resolved enabled state. The
 * live connection status (connected / needs-auth / …) is NOT here — it comes
 * from the running session's `system/init` and is merged by the UI.
 */
export type McpServerInfo = { name: string; scope: ExtScope; 
/**
 * `"stdio"` | `"http"` | `"sse"` when declared (stdio is the implicit default).
 */
transport: string | null; 
/**
 * Launch command for a stdio server (e.g. `npx`, `railway`). Args omitted
 * (may carry secrets).
 */
command: string | null; 
/**
 * Endpoint for an http/sse server, with any query string stripped.
 */
url: string | null; 
/**
 * Plugin id (`<plugin>@<marketplace>`) when `scope == Plugin`.
 */
source: string | null; 
/**
 * Resolved on-disk enabled state for this repo (project toggles applied).
 */
enabled: boolean }
/**
 * Live status of one MCP server, queried on demand from the running session via
 * the `mcp_status` control request (NOT the `system/init` snapshot, which is
 * point-in-time and shows servers stuck at `pending`). This is the authoritative
 * real-time picture the conversation view shows — including claude.ai-hosted
 * connectors that only exist in the live session. Distinct from the *configured*
 * on-disk [`crate::extensions::McpServerInfo`].
 */
export type McpServerLive = { 
/**
 * Server name as the session reports it (`plugin:<p>:<s>` for a plugin server,
 * `claude.ai <Name>` for a connector).
 */
name: string; 
/**
 * `connected` / `disconnected` / `pending` / `checking_status` / `failed` /
 * `needs-auth` / `disabled`.
 */
status: string; 
/**
 * Where it comes from: `user` / `project` / `local` / `dynamic` (plugin) /
 * `claudeai` (account connector). `None` if absent.
 */
scope: string | null; 
/**
 * Transport from the server config (`stdio` / `http` / `sse`).
 */
transport: string | null; 
/**
 * Launch command for a stdio server (args omitted — may carry secrets).
 */
command: string | null; 
/**
 * Endpoint for an http/sse server.
 */
url: string | null; 
/**
 * Number of tools the server currently exposes (0 unless connected).
 */
tool_count: number; 
/**
 * Names of the tools the server exposes (empty unless connected) — shown when
 * the user expands a server row.
 */
tools: string[] }
/**
 * One authoritative content block of an assistant message.
 */
export type NormalizedBlock = { type: "text"; text: string } | { type: "thinking"; text: string } | { type: "tool_use"; id: string; name: string; input: JsonValue } | 
/**
 * Any block kind we do not specialize (images, documents, …) kept raw.
 */
{ type: "other"; raw: JsonValue }
/**
 * A UI decision for a `can_use_tool` prompt (the `answer_permission` command
 * input). Tagged on `behavior` to mirror the protocol's result shape.
 */
export type PermissionDecision = 
/**
 * Allow the tool. `updated_input` optionally rewrites the tool input;
 * `None` echoes the original input unchanged.
 */
{ behavior: "allow"; updated_input: JsonValue | null } | 
/**
 * Deny the tool with a human-readable reason.
 */
{ behavior: "deny"; message: string }
/**
 * Permission mode, switched at runtime via `set_permission_mode` (spec §4.5).
 * The wire tokens are exactly these camelCase strings.
 */
export type PermissionMode = "acceptEdits" | "auto" | "bypassPermissions" | "default" | "dontAsk" | "plan"
/**
 * A `can_use_tool` permission prompt surfaced to the UI. The UI answers it via
 * the `answer_permission` command, echoing `request_id`.
 */
export type PermissionRequestPayload = { request_id: string; tool_name: string; tool_use_id: string; input: JsonValue; title: string | null; description: string | null; 
/**
 * CLI-provided suggestions (kept raw).
 */
suggestions: JsonValue }
/**
 * The full persisted snapshot the UI hydrates from at boot.
 */
export type PersistedState = { repos: RepoRecord[]; conversations: ConversationRecord[]; 
/**
 * Stable id of the conversation that was active when last persisted.
 */
active_id: string | null }
/**
 * Real plan-usage snapshot: the two subscription windows, each with a fill %.
 * A window is `None` when the endpoint did not report it.
 */
export type PlanUsage = { five_hour: UsageWindow | null; seven_day: UsageWindow | null }
/**
 * Everything ONE plugin provides — for the per-plugin explorer (click a plugin →
 * browse its skills / sub-agents / MCP servers, like Claude.ai's Customize panel).
 * 
 * Scanned straight from the plugin's install dir REGARDLESS of its enabled state:
 * a disabled plugin must still be browsable. This is why it is a separate read
 * from [`list_extensions`], which only folds an *enabled* plugin's contributions
 * into the active snapshot.
 */
export type PluginContents = { skills: SkillInfo[]; agents: AgentInfo[]; mcp_servers: McpServerInfo[] }
/**
 * One installed plugin relevant to a repository (user-global, or project/local
 * scoped to this repo).
 */
export type PluginInfo = { 
/**
 * `<plugin>@<marketplace>` — the key used in `enabledPlugins`.
 */
id: string; name: string; marketplace: string; version: string | null; description: string | null; enabled: boolean; scope: ExtScope; 
/**
 * What the plugin provides (scanned from its cache dir), regardless of
 * enabled state — so the UI can show "5 skills" even when toggled off.
 */
skill_count: number; agent_count: number; command_count: number; mcp_count: number }
/**
 * Typed return value of `ping`. Proves React -> Rust (typed command).
 */
export type Pong = { ok: boolean; echo: string; at_ms: number }
/**
 * Subscription rate-limit status, normalized from `rate_limit_event.rate_limit_info`.
 * Carries only what the stream-json protocol exposes: the coarse `status`, the
 * reset time, the window type, and whether overage is active. The precise usage
 * percentage is NOT in the stream (it comes from `GET /api/oauth/usage`).
 */
export type RateLimitSnapshot = { 
/**
 * `"allowed"` (no warning), `"allowed_warning"` (approaching), `"rejected"` (limited), …
 */
status: string | null; 
/**
 * Unix epoch seconds when the current window resets.
 */
resets_at: number | null; 
/**
 * Which window this refers to: `"five_hour"`, `"seven_day"`, …
 */
limit_type: string | null; 
/**
 * `true` while the account is spending overage credits.
 */
using_overage: boolean }
/**
 * A working folder a conversation can be opened in.
 */
export type RepoRecord = { id: string; path: string; 
/**
 * Unix ms timestamp the repo was first added.
 */
added_at: number }
/**
 * The session's available slash commands (one-shot, at `initialize`). Drives the
 * composer's `/` autocomplete menu.
 */
export type SessionCommandsEvent = { session: string; commands: SlashCommand[] }
/**
 * A normalized conversation item to render (text delta, assistant message,
 * tool result, turn result, …).
 */
export type SessionMessageEvent = { session: string; item: ConversationItem }
/**
 * A `can_use_tool` permission prompt awaiting a decision.
 */
export type SessionPermissionEvent = { session: string; request: PermissionRequestPayload }
/**
 * A session's lifecycle / identity changed.
 */
export type SessionStateEvent = { session: string; state: SessionStatePayload }
/**
 * Coarse lifecycle + identity of a session, emitted whenever it changes.
 */
export type SessionStatePayload = { 
/**
 * `true` while a turn is in flight (between a user message and its `result`).
 */
busy: boolean; 
/**
 * The CLI-assigned conversation id (from `system/init`); enables `--resume`.
 */
session_id: string | null; 
/**
 * The session's CURRENT working directory (from `system/init`). The CLI can
 * move it mid-session when the agent calls `EnterWorktree`/`ExitWorktree`, so
 * the UI reads this — not the static spawn cwd — to show which worktree the
 * conversation is in right now.
 */
cwd: string | null; 
/**
 * Current model id (from `system/init`, refined by the `get_settings`
 * read-back to the resolved id, e.g. `claude-opus-4-8[1m]`).
 */
model: string | null; 
/**
 * Current permission mode (from `system/init` / the `set_permission_mode` ack).
 */
permission_mode: string | null; 
/**
 * Current reasoning-effort level (`low`/`medium`/`high`/`xhigh`). NOT carried
 * by `system/init` — sourced from the `get_settings` control read-back (and the
 * spawn seed). `None` until the first read-back. Drives the effort gauge.
 */
effort: string | null; 
/**
 * Whether "ultracode" (xhigh effort + standing dynamic-workflow orchestration)
 * is active right now. A SEPARATE boolean flag in the CLI, not an effort value.
 */
ultracode: boolean; 
/**
 * Fine-grained activity hint from `system/status` (e.g. `"requesting"`).
 */
activity: string | null; 
/**
 * `true` while waiting on the user to answer a permission prompt.
 */
awaiting_permission: boolean; 
/**
 * `true` once the session has ended (the `claude` process exited or was
 * stopped). A final state event with this set lets the UI mark the session
 * dead instead of showing it as live forever.
 */
ended: boolean; 
/**
 * Tokens occupying the model's context window right now: the last model call's
 * `input + cache_creation + cache_read` (from `message_start` live, then the
 * `result`). `None` until the first turn reports usage. Drives the context ring.
 */
context_tokens: number | null; 
/**
 * Size of the active model's context window (from `result.modelUsage[…].contextWindow`,
 * e.g. 200k or 1M for Opus in 1M mode). `None` until a `result` reports it; once
 * known it is kept across turns that omit it. The ring's denominator.
 */
context_window: number | null; 
/**
 * Latest subscription rate-limit snapshot (from `rate_limit_event`). `None` until
 * the CLI emits one. NOTE: the stream only carries status + reset, NOT a usage
 * percentage — that lives behind the `/api/oauth/usage` endpoint (separate task).
 */
rate_limit: RateLimitSnapshot | null }
/**
 * A background task (sub-agent / workflow / Monitor / background Bash) was created
 * or changed state. Emitted on every `task_*` transition, keyed (inside the
 * payload) by `task_id`, so the UI tracks the live fleet of background tasks.
 */
export type SessionTaskEvent = { session: string; task: BackgroundTask }
/**
 * A model-generated conversation title arrived (from a `generate_session_title`
 * control response). The UI maps `session` (handle) → conversation and applies the
 * title as the name UNLESS the user set a custom title in the meantime. `seq` is the
 * monotonic per-conversation tag the UI sent: it applies a title only if `seq` is
 * newer than the last applied, so an out-of-order (stale) response can't overwrite a
 * fresher title.
 */
export type SessionTitleEvent = { session: string; title: string; seq: number }
/**
 * One skill available to a repository (file-based or plugin-provided).
 */
export type SkillInfo = { name: string; description: string | null; scope: ExtScope; 
/**
 * Plugin id when plugin-provided; `None` for a user/project file skill.
 */
source: string | null; 
/**
 * Absolute path to the skill's `SKILL.md` — the UI reads it to render a clean
 * markdown view of the skill.
 */
path: string }
/**
 * One slash command available in the session, as advertised by the CLI in its
 * `initialize` control response (spec §4.4). The same shape the official VS Code
 * extension consumes to drive its `/` autocomplete menu. `name` carries NO
 * leading slash (e.g. `"compact"`, `"tosse-workflow:pickup"`).
 */
export type SlashCommand = { name: string; 
/**
 * Human-readable description (may be empty). For skills, the CLI prefixes a
 * `(plugin)` / `(dynamic workflow)` source hint.
 */
description: string; 
/**
 * Hint for the command's arguments (e.g. `"<task_id>"`), empty when none.
 */
argument_hint: string }
/**
 * An integrated terminal's shell exited (EOF on the PTY). One-shot, keyed by id;
 * the front marks that terminal done and offers to restart it on re-open.
 */
export type TerminalExitEvent = { id: string }
/**
 * A chunk of output from an integrated terminal's PTY, base64-encoded. Base64
 * (not a `number[]` or a per-chunk lossy string) keeps the byte stream exact and
 * compact — xterm's own decoder reassembles UTF-8 sequences split across chunks.
 * Keyed by the terminal `id` so the front routes it to the right xterm instance.
 */
export type TerminalOutputEvent = { id: string; data: string }
/**
 * Emitted periodically by a Rust timer. Proves Rust -> React (typed event).
 */
export type TickEvent = { seq: number; message: string }
/**
 * Why fetching the real usage % failed, typed so the UI can give a tailored next
 * step instead of a dead-end "unavailable". Tagged on `kind` → a clean TS union.
 */
export type UsageError = 
/**
 * No token in the file nor the Keychain (user never logged in via the CLI).
 */
{ kind: "no_token" } | 
/**
 * The Keychain refused access (unsigned app not in the item ACL, or cancelled).
 */
{ kind: "keychain_denied"; detail: string } | 
/**
 * Endpoint rejected the token (HTTP 401/403): expired or revoked.
 */
{ kind: "unauthorized"; status: number } | 
/**
 * The usage endpoint is itself rate-limited (HTTP 429). `retry_after` = seconds
 * from the `Retry-After` header when present. Do NOT hammer it — back off.
 */
{ kind: "rate_limited"; retry_after: number | null } | 
/**
 * Any other non-success HTTP status from the endpoint (carries status + body).
 */
{ kind: "http"; status: number; body: string } | 
/**
 * Network-level failure (DNS, TLS, timeout, offline).
 */
{ kind: "network"; detail: string } | 
/**
 * Response received but unparseable into the expected shape (carries body).
 */
{ kind: "parse"; body: string }
/**
 * One rate-limit window's real fill: `used_percentage` (0–100) + optional reset as a
 * raw timestamp string (ISO 8601, or epoch-seconds digits for the alternate shape) —
 * the frontend converts it with the JS `Date` parser.
 */
export type UsageWindow = { used_percentage: number; resets_at: string | null }
/**
 * One phase of a workflow run, from a `workflows/wf_<id>.json` manifest.
 */
export type WorkflowPhase = { title: string; detail: string | null }
/**
 * A workflow run's manifest (`workflows/wf_<id>.json`), the data model behind the
 * `/workflows`-style view. Field names mirror the on-disk camelCase manifest. The
 * dynamic, per-entry-shaped `workflowProgress` and `result` are kept raw
 * ([`Value`]) — the Workflow display task types them.
 */
export type WorkflowRun = { runId: string; taskId: string | null; status: string | null; workflowName: string | null; defaultModel: string | null; durationMs: number | null; agentCount: number | null; totalTokens: number | null; totalToolCalls: number | null; summary: string | null; 
/**
 * `#[serde(default)]` alone covers a MISSING key, but an explicit `"phases":null`
 * would still fail the WHOLE manifest parse (blanking the entire workflow view).
 * `deserialize_null_default` maps null → empty, mirroring the stream structs'
 * `Option` null-tolerance ([`super::protocol::TaskNotificationMsg::usage`]).
 */
phases?: WorkflowPhase[]; 
/**
 * Array of `{type:"workflow_phase"|"workflow_agent", …}` entries — kept raw.
 */
workflowProgress?: JsonValue; 
/**
 * The workflow's final return value — kept raw.
 */
result?: JsonValue }
/**
 * Identity of one worktree of a repository (the cheap, always-listed part).
 * 
 * A repository has exactly one MAIN worktree (the original checkout) plus any
 * number of LINKED worktrees created with `git worktree add`. Each is a
 * separate working directory sharing the same `.git` history — which is what
 * lets several `claude` agents work the same repo in parallel without stepping
 * on each other.
 */
export type WorktreeInfo = { 
/**
 * Absolute path of the worktree's working directory.
 */
path: string; 
/**
 * Short branch name (`refs/heads/` stripped). `None` when detached or bare.
 */
branch: string | null; 
/**
 * Full HEAD commit oid. `None` for the bare entry.
 */
head: string | null; 
/**
 * The repository's MAIN worktree (the first entry `git` lists). The one
 * worktree that can never be removed.
 */
is_main: boolean; 
/**
 * HEAD is detached (no branch checked out).
 */
is_detached: boolean; 
/**
 * Locked via `git worktree lock` (a removal needs `--force`).
 */
is_locked: boolean; 
/**
 * The bare repository entry (has no working tree of its own).
 */
is_bare: boolean }
/**
 * Working-tree status of one worktree (the heavier, on-demand part — one extra
 * `git` call per worktree, so it is fetched lazily by the manager, never for
 * the always-on indicator).
 */
export type WorktreeStatus = { 
/**
 * At least one tracked file has staged or unstaged modifications.
 */
dirty: boolean; 
/**
 * At least one untracked file is present.
 */
untracked: boolean; 
/**
 * Number of entries `git status --porcelain` reports (changed + untracked).
 */
changed_files: number; 
/**
 * Commits ahead of the branch's upstream. `None` when no upstream is set.
 */
ahead: number | null; 
/**
 * Commits behind the branch's upstream. `None` when no upstream is set.
 */
behind: number | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
