// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async ping(msg: string) : Promise<Pong> {
    return await TAURI_INVOKE("ping", { msg });
},
/**
 * Start a new `claude` session rooted at `repo_path`, applying this conversation's
 * controls (model / effort / permission mode / ultracode) at spawn so the live
 * stream starts in EXACTLY the state the UI shows — never the old hardcoded
 * defaults. Returns our session id; conversation/state/permission events are
 * emitted on the Tauri event bus.
 */
async spawnSession(repoPath: string, resume: string | null, model: string | null, effort: string | null, permissionMode: string | null, ultracode: boolean) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spawn_session", { repoPath, resume, model, effort, permissionMode, ultracode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch the slash commands available in `cwd` WITHOUT starting a persistent
 * session. Spawns a short-lived `claude`, performs the `initialize` handshake
 * (spec §4.4), reads the advertised commands from its `control_response`, and
 * tears the process down. This lets the composer populate its `/` autocomplete
 * before the lazy session spawn — so typing `/pickup` as the very first thing
 * works — without leaving a process alive. Returns an empty list if the
 * handshake does not complete within the deadline (the live session, spawned on
 * the first message, will still emit commands later via `SessionCommandsEvent`).
 */
async fetchSlashCommands(cwd: string) : Promise<Result<SlashCommand[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_slash_commands", { cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rebuild a resumed conversation's history from Claude's on-disk transcript.
 * 
 * `claude --resume` does not re-stream past messages, so the live event path
 * delivers nothing for an existing conversation. The UI calls this after
 * re-spawning a session to replay its history into the store. An absent
 * transcript yields an empty list (not an error). File IO runs off the async
 * runtime via `spawn_blocking` so a large transcript never stalls it.
 */
async loadSessionHistory(sessionId: string) : Promise<Result<ConversationItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_session_history", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a resumed conversation's current context fill (used tokens + window) from
 * its on-disk transcript, so the UI can show the context ring as soon as the
 * conversation is opened / its stream turned on — before the first new turn streams
 * live usage. An absent transcript yields all-`None` (not an error). File IO runs
 * off the async runtime via `spawn_blocking`.
 */
async loadSessionContext(sessionId: string) : Promise<Result<ContextFill, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_session_context", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load a sub-agent's (`Agent` tool, or a workflow agent) full transcript,
 * normalized into the same items the live conversation renders. Empty if absent.
 */
async loadSubagentTranscript(sessionId: string, agentId: string) : Promise<Result<ConversationItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_subagent_transcript", { sessionId, agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load a workflow run's manifest (`workflows/<run_id>.json`). `null` if absent.
 */
async loadWorkflowRun(sessionId: string, runId: string) : Promise<Result<WorkflowRun | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_workflow_run", { sessionId, runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the current contents of a background task's output file
 * (`tasks/<task_id>.output`, the sink for background `Bash` and `Monitor`). `null`
 * if absent. One-shot read — live tailing is layered on by the display task.
 */
async readTaskOutput(sessionId: string, taskId: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_task_output", { sessionId, taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a user turn to a session.
 */
async sendMessage(session: string, text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_message", { session, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Answer a pending `can_use_tool` permission prompt (allow / deny).
 */
async answerPermission(session: string, requestId: string, decision: PermissionDecision) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("answer_permission", { session, requestId, decision }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Switch the session's permission mode at runtime.
 */
async setPermissionMode(session: string, mode: PermissionMode) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_permission_mode", { session, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Switch the session's active model at runtime (`set_model`).
 */
async setModel(session: string, model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_model", { session, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the session's reasoning effort level at runtime (`apply_flag_settings`).
 * Rejects an invalid level BEFORE sending: the CLI silently swallows anything
 * outside low/medium/high/xhigh, so an unvalidated value would no-op without any
 * error — exactly the silent failure we must avoid.
 */
async setEffortLevel(session: string, level: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_effort_level", { session, level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enable "ultracode" (xhigh effort + standing dynamic-workflow orchestration) at
 * runtime. Disabling is done by selecting any plain effort level via
 * [`set_effort_level`], which clears the flag.
 */
async setUltracode(session: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_ultracode", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Interrupt the current turn (without killing the process).
 */
async interruptSession(session: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("interrupt_session", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tear a session down and remove it from the registry.
 */
async stopSession(session: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_session", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open the OS terminal on this conversation: resume it as an interactive
 * `claude` session (`claude --resume <session_id>`) in its working directory.
 * 
 * This launches a *separate*, user-driven `claude` outside the app — the same
 * session id the supervisor drives, resumed from Claude's on-disk transcript
 * (not the live stream). macOS only for now (drives Terminal.app via
 * AppleScript); other platforms return an error the UI can surface. The
 * blocking `osascript` call runs off the async runtime via `spawn_blocking`.
 */
async openInTerminal(cwd: string, sessionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_in_terminal", { cwd, sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Bounce the app's Dock icon (macOS) / flash the taskbar (other platforms) to
 * get the user's attention when an agent finishes or needs input while the app
 * is in the background. `critical` bounces repeatedly until the app is focused
 * (a permission/question is waiting); otherwise it bounces once (a turn ended).
 * The OS clears the request automatically when the window regains focus, so the
 * front never has to cancel it. A no-op if the main window is gone.
 */
async requestUserAttention(critical: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_user_attention", { critical }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List every worktree of the repository `repo_path` lives in (main first).
 */
async listWorktrees(repoPath: string) : Promise<Result<WorktreeInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_worktrees", { repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Working-tree status of one worktree (dirty / untracked / ahead-behind).
 */
async worktreeStatus(worktreePath: string) : Promise<Result<WorktreeStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("worktree_status", { worktreePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a worktree for `branch` (new branch off `base_ref` when `new_branch`,
 * else an existing branch). Returns the created worktree's info.
 */
async createWorktree(repoPath: string, branch: string, baseRef: string | null, newBranch: boolean) : Promise<Result<WorktreeInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_worktree", { repoPath, branch, baseRef, newBranch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a worktree. `git` refuses a dirty or main worktree unless `force`,
 * which the UI only passes after an explicit, separate confirmation.
 */
async removeWorktree(repoPath: string, worktreePath: string, force: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_worktree", { repoPath, worktreePath, force }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether a filesystem path currently exists. Used to detect a conversation
 * whose worktree cwd was removed, so the UI can fall back to the repo's main
 * checkout instead of failing to spawn `claude` in a directory that is gone.
 */
async pathExists(path: string) : Promise<boolean> {
    return await TAURI_INVOKE("path_exists", { path });
},
/**
 * List one directory level (dirs first, then files, alpha) for the file tree.
 */
async readDir(path: string) : Promise<Result<FsEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_dir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a file into the editor (guards binary / oversize — see `fs::read_file`).
 */
async readFile(path: string) : Promise<Result<FileContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write the editor buffer back to disk (save).
 */
async writeFile(path: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_file", { path, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start (or replace) the live watch on `path` — the editor's current working
 * directory. Changes under it arrive as a debounced `FsChangeEvent`.
 */
async watchDir(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("watch_dir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the live filesystem watch (editor panel closed / no conversation shown).
 */
async unwatchDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unwatch_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load the persisted repos + conversations + active selection (UI hydration at boot).
 */
async loadPersistedState() : Promise<Result<PersistedState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_persisted_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Insert or update a repo (idempotent by id).
 */
async upsertRepo(repo: RepoRecord) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_repo", { repo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a repo; its conversations cascade away.
 */
async deleteRepo(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_repo", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Insert or update a conversation's metadata (idempotent by stable id).
 */
async upsertConversation(conversation: ConversationRecord) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_conversation", { conversation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Forget a conversation's metadata.
 */
async deleteConversation(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_conversation", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist (or clear, with `null`) the active conversation's stable id.
 */
async setActiveConversation(id: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_conversation", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drop ALL persisted data (dev escape hatch + Settings "drop all"). Claude's
 * on-disk transcripts are untouched.
 */
async wipeAllData() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wipe_all_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
fsChangeEvent: FsChangeEvent,
sessionCommandsEvent: SessionCommandsEvent,
sessionMessageEvent: SessionMessageEvent,
sessionPermissionEvent: SessionPermissionEvent,
sessionStateEvent: SessionStateEvent,
sessionTaskEvent: SessionTaskEvent,
tickEvent: TickEvent
}>({
fsChangeEvent: "fs-change-event",
sessionCommandsEvent: "session-commands-event",
sessionMessageEvent: "session-message-event",
sessionPermissionEvent: "session-permission-event",
sessionStateEvent: "session-state-event",
sessionTaskEvent: "session-task-event",
tickEvent: "tick-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * A normalized background task, keyed by `task_id` and updated in place as its
 * `task_*` lifecycle events arrive. The single model behind the (future) sub-agent /
 * workflow / Monitor / background-Bash views — the rich per-producer detail (full
 * transcript, manifest, output) is read from disk on demand (see
 * [`super::subagents`]), never carried here.
 */
export type BackgroundTask = { 
/**
 * Stable id that ties every `task_*` event of this task together.
 */
task_id: string; kind: BackgroundTaskKind; 
/**
 * The `tool_use` block that spawned the task (== `parent_tool_use_id` of any
 * streamed child content). Lets the UI anchor the task under its tool card.
 */
tool_use_id: string | null; 
/**
 * Human label (the `description`: a sub-agent's task, a Bash command, …).
 */
label: string | null; 
/**
 * Sub-agent type (`Agent` only, e.g. `"Explore"`).
 */
subagent_type: string | null; 
/**
 * The sub-agent's id (`Agent` only), i.e. the key for [`super::subagents::load_subagent_transcript`].
 * Derived from the `output_file` basename (`subagents/agent-<agentId>.jsonl`), since
 * the wire carries it only inside that path. Lets the UI drill into the transcript
 * without re-parsing the path itself.
 */
agent_id: string | null; status: BackgroundTaskStatus; 
/**
 * Latest live progress text (`Workflow`: `"<phase>: <label>"`).
 */
progress: string | null; 
/**
 * Total tokens used (from the `task_notification` usage roll-up).
 */
tokens: number | null; 
/**
 * Tool-call count (from the usage roll-up).
 */
tool_uses: number | null; 
/**
 * Wall-clock duration in ms (from the usage roll-up).
 */
duration_ms: number | null; 
/**
 * End-of-task human summary (from the `task_notification`).
 */
summary: string | null; 
/**
 * On-disk file holding the task's full output: `tasks/<id>.output` for
 * Bash-bg/Monitor, the sub-agent transcript for `Agent`.
 */
output_file: string | null }
/**
 * Which producer a background task came from. The `claude` binary runs ONE generic
 * background-task system for four producers; we tell them apart from `task_type`
 * plus the correlated `tool_use` name (see [`super::assembler`]).
 */
export type BackgroundTaskKind = 
/**
 * A sub-agent launched by the `Agent` tool (`task_type:"local_agent"`).
 */
"agent" | 
/**
 * A dynamic-workflow run launched by the `Workflow` tool.
 */
"workflow" | 
/**
 * A shell command launched by `Bash` with `run_in_background:true`.
 */
"bash" | 
/**
 * A live watch launched by the `Monitor` tool.
 */
"monitor" | 
/**
 * A background task whose producer could not be classified yet.
 */
"other"
/**
 * Coarse lifecycle status of a background task, normalized from `task_*` events.
 */
export type BackgroundTaskStatus = 
/**
 * Created and not yet finished (`task_started`, or a non-terminal patch).
 */
"running" | 
/**
 * Finished successfully (`patch.status`/notification `"completed"`).
 */
"completed" | 
/**
 * Finished with an error (`"failed"`/`"error"`).
 */
"failed" | 
/**
 * Cancelled via `TaskStop` / session end (`"stopped"`/`"cancelled"`).
 */
"stopped"
/**
 * Context-meter seed for a conversation, read from its on-disk transcript so the
 * ring shows the real fill the moment a conversation is opened / its stream turned
 * on — before the first new turn streams live usage. `context_window` is the model's
 * provisional window (the transcript carries no authoritative `modelUsage`); the
 * first live `result` later refines it.
 */
export type ContextFill = { context_tokens: number | null; context_window: number | null }
/**
 * A normalized conversation event the UI applies incrementally. Tagged on
 * `kind` so the TS side is a simple discriminated union.
 */
export type ConversationItem = 
/**
 * An assistant turn began (from `stream_event/message_start`).
 */
{ kind: "message_started"; id: string; role: string; parent_tool_use_id: string | null } | 
/**
 * Live assistant text token(s) (from `content_block_delta/text_delta`).
 */
{ kind: "text_delta"; message_id: string | null; text: string } | 
/**
 * Live extended-thinking token(s).
 */
{ kind: "thinking_delta"; message_id: string | null; text: string } | 
/**
 * A past user turn, replayed from Claude's transcript when a conversation is
 * resumed. The live path never emits this — the UI adds user turns
 * optimistically on send — so it only appears during history restore.
 */
{ kind: "user_message"; id: string; text: string; parent_tool_use_id: string | null } | 
/**
 * The authoritative assembled assistant message (text + tool_use blocks).
 * Carries the same `id` as the streamed `message_start` — the UI reconciles.
 */
{ kind: "assistant_message"; id: string; blocks: NormalizedBlock[]; parent_tool_use_id: string | null } | 
/**
 * A tool result, delivered by the CLI as a `user` message.
 */
{ kind: "tool_result"; tool_use_id: string; content: JsonValue; is_error: boolean; parent_tool_use_id: string | null } | 
/**
 * End of a turn (`result`).
 */
{ kind: "turn_result"; subtype: string; is_error: boolean; result: JsonValue | null; total_cost_usd: number | null; num_turns: number | null; duration_ms: number | null } | 
/**
 * A non-conversational system notice (compact boundary, sub-agent task
 * lifecycle, …) surfaced raw for now.
 */
{ kind: "notice"; subtype: string; detail: JsonValue }
/**
 * A conversation's persisted metadata.
 * 
 * The stable `id` is the identity the whole app keys off. It is deliberately
 * distinct from the ephemeral live session handle (`session-N`), which is
 * in-memory only and never persisted — so other services can reference a
 * conversation by an id that survives restarts.
 */
export type ConversationRecord = { id: string; name: string; 
/**
 * FK to [`RepoRecord::id`].
 */
repo_id: string; 
/**
 * Absolute path the session was spawned in.
 */
cwd: string; 
/**
 * Unix ms timestamp the conversation was created.
 */
created_at: number; 
/**
 * Unix ms timestamp of the conversation's last activity — the last message
 * sent OR received. Drives the sidebar's most-recent-first ordering. Bumped
 * by the UI on each user send and turn result; pre-existing rows (created
 * before this column) are backfilled from the transcript mtime at boot (see
 * [`super::db::Store::backfill_last_activity`]).
 */
last_activity_at: number; 
/**
 * Claude's own session UUID (from system/init) — used for `--resume`.
 */
session_id: string | null; 
/**
 * Per-conversation controls, persisted so they survive a restart and are
 * re-applied at the next (lazy) spawn. While a session is LIVE its own state
 * (get_settings / system/init) is the source of truth; these hold the
 * last-known values to restore from. `None`/`false` fall back to the product
 * defaults at spawn (opus / xhigh / default).
 * 
 * `model` is the CLI alias chosen in the UI (e.g. "opus"); `effort` is one of
 * low/medium/high/xhigh; `ultracode` is the separate xhigh+orchestration tier;
 * `permission_mode` is one of the CLI modes (default/plan/acceptEdits/auto/…).
 */
model: string | null; effort: string | null; ultracode: boolean; permission_mode: string | null }
/**
 * A file's contents plus the guards the editor needs: `too_large` (skipped, over
 * [`MAX_FILE_BYTES`]) and `binary` (a NUL byte was found — not shown as text).
 * In both guard cases `content` is empty.
 */
export type FileContent = { path: string; content: string; too_large: boolean; binary: boolean; size: number }
/**
 * Coalesced filesystem change notification for the editor panel: the (de-noised,
 * debounced) set of paths that changed under the watched working directory. The
 * UI reloads any open file in this set and refreshes any expanded tree dirs it
 * touches. Not session-keyed: there is a single active watch (the shown cwd).
 */
export type FsChangeEvent = { paths: string[] }
/**
 * One immediate child of a listed directory. The tree expands lazily (a click
 * reads exactly one level), so a huge repo never reads more than what is shown.
 */
export type FsEntry = { name: string; path: string; is_dir: boolean }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * One authoritative content block of an assistant message.
 */
export type NormalizedBlock = { type: "text"; text: string } | { type: "thinking"; text: string } | { type: "tool_use"; id: string; name: string; input: JsonValue } | 
/**
 * Any block kind we do not specialize (images, documents, …) kept raw.
 */
{ type: "other"; raw: JsonValue }
/**
 * A UI decision for a `can_use_tool` prompt (the `answer_permission` command
 * input). Tagged on `behavior` to mirror the protocol's result shape.
 */
export type PermissionDecision = 
/**
 * Allow the tool. `updated_input` optionally rewrites the tool input;
 * `None` echoes the original input unchanged.
 */
{ behavior: "allow"; updated_input: JsonValue | null } | 
/**
 * Deny the tool with a human-readable reason.
 */
{ behavior: "deny"; message: string }
/**
 * Permission mode, switched at runtime via `set_permission_mode` (spec §4.5).
 * The wire tokens are exactly these camelCase strings.
 */
export type PermissionMode = "acceptEdits" | "auto" | "bypassPermissions" | "default" | "dontAsk" | "plan"
/**
 * A `can_use_tool` permission prompt surfaced to the UI. The UI answers it via
 * the `answer_permission` command, echoing `request_id`.
 */
export type PermissionRequestPayload = { request_id: string; tool_name: string; tool_use_id: string; input: JsonValue; title: string | null; description: string | null; 
/**
 * CLI-provided suggestions (kept raw).
 */
suggestions: JsonValue }
/**
 * The full persisted snapshot the UI hydrates from at boot.
 */
export type PersistedState = { repos: RepoRecord[]; conversations: ConversationRecord[]; 
/**
 * Stable id of the conversation that was active when last persisted.
 */
active_id: string | null }
/**
 * Typed return value of `ping`. Proves React -> Rust (typed command).
 */
export type Pong = { ok: boolean; echo: string; at_ms: number }
/**
 * Subscription rate-limit status, normalized from `rate_limit_event.rate_limit_info`.
 * Carries only what the stream-json protocol exposes: the coarse `status`, the
 * reset time, the window type, and whether overage is active. The precise usage
 * percentage is NOT in the stream (it comes from `GET /api/oauth/usage`).
 */
export type RateLimitSnapshot = { 
/**
 * `"allowed"` (no warning), `"allowed_warning"` (approaching), `"rejected"` (limited), …
 */
status: string | null; 
/**
 * Unix epoch seconds when the current window resets.
 */
resets_at: number | null; 
/**
 * Which window this refers to: `"five_hour"`, `"seven_day"`, …
 */
limit_type: string | null; 
/**
 * `true` while the account is spending overage credits.
 */
using_overage: boolean }
/**
 * A working folder a conversation can be opened in.
 */
export type RepoRecord = { id: string; path: string; 
/**
 * Unix ms timestamp the repo was first added.
 */
added_at: number }
/**
 * The session's available slash commands (one-shot, at `initialize`). Drives the
 * composer's `/` autocomplete menu.
 */
export type SessionCommandsEvent = { session: string; commands: SlashCommand[] }
/**
 * A normalized conversation item to render (text delta, assistant message,
 * tool result, turn result, …).
 */
export type SessionMessageEvent = { session: string; item: ConversationItem }
/**
 * A `can_use_tool` permission prompt awaiting a decision.
 */
export type SessionPermissionEvent = { session: string; request: PermissionRequestPayload }
/**
 * A session's lifecycle / identity changed.
 */
export type SessionStateEvent = { session: string; state: SessionStatePayload }
/**
 * Coarse lifecycle + identity of a session, emitted whenever it changes.
 */
export type SessionStatePayload = { 
/**
 * `true` while a turn is in flight (between a user message and its `result`).
 */
busy: boolean; 
/**
 * The CLI-assigned conversation id (from `system/init`); enables `--resume`.
 */
session_id: string | null; 
/**
 * The session's CURRENT working directory (from `system/init`). The CLI can
 * move it mid-session when the agent calls `EnterWorktree`/`ExitWorktree`, so
 * the UI reads this — not the static spawn cwd — to show which worktree the
 * conversation is in right now.
 */
cwd: string | null; 
/**
 * Current model id (from `system/init`, refined by the `get_settings`
 * read-back to the resolved id, e.g. `claude-opus-4-8[1m]`).
 */
model: string | null; 
/**
 * Current permission mode (from `system/init` / the `set_permission_mode` ack).
 */
permission_mode: string | null; 
/**
 * Current reasoning-effort level (`low`/`medium`/`high`/`xhigh`). NOT carried
 * by `system/init` — sourced from the `get_settings` control read-back (and the
 * spawn seed). `None` until the first read-back. Drives the effort gauge.
 */
effort: string | null; 
/**
 * Whether "ultracode" (xhigh effort + standing dynamic-workflow orchestration)
 * is active right now. A SEPARATE boolean flag in the CLI, not an effort value.
 */
ultracode: boolean; 
/**
 * Fine-grained activity hint from `system/status` (e.g. `"requesting"`).
 */
activity: string | null; 
/**
 * `true` while waiting on the user to answer a permission prompt.
 */
awaiting_permission: boolean; 
/**
 * `true` once the session has ended (the `claude` process exited or was
 * stopped). A final state event with this set lets the UI mark the session
 * dead instead of showing it as live forever.
 */
ended: boolean; 
/**
 * Tokens occupying the model's context window right now: the last model call's
 * `input + cache_creation + cache_read` (from `message_start` live, then the
 * `result`). `None` until the first turn reports usage. Drives the context ring.
 */
context_tokens: number | null; 
/**
 * Size of the active model's context window (from `result.modelUsage[…].contextWindow`,
 * e.g. 200k or 1M for Opus in 1M mode). `None` until a `result` reports it; once
 * known it is kept across turns that omit it. The ring's denominator.
 */
context_window: number | null; 
/**
 * Latest subscription rate-limit snapshot (from `rate_limit_event`). `None` until
 * the CLI emits one. NOTE: the stream only carries status + reset, NOT a usage
 * percentage — that lives behind the `/api/oauth/usage` endpoint (separate task).
 */
rate_limit: RateLimitSnapshot | null }
/**
 * A background task (sub-agent / workflow / Monitor / background Bash) was created
 * or changed state. Emitted on every `task_*` transition, keyed (inside the
 * payload) by `task_id`, so the UI tracks the live fleet of background tasks.
 */
export type SessionTaskEvent = { session: string; task: BackgroundTask }
/**
 * One slash command available in the session, as advertised by the CLI in its
 * `initialize` control response (spec §4.4). The same shape the official VS Code
 * extension consumes to drive its `/` autocomplete menu. `name` carries NO
 * leading slash (e.g. `"compact"`, `"tosse-workflow:pickup"`).
 */
export type SlashCommand = { name: string; 
/**
 * Human-readable description (may be empty). For skills, the CLI prefixes a
 * `(plugin)` / `(dynamic workflow)` source hint.
 */
description: string; 
/**
 * Hint for the command's arguments (e.g. `"<task_id>"`), empty when none.
 */
argument_hint: string }
/**
 * Emitted periodically by a Rust timer. Proves Rust -> React (typed event).
 */
export type TickEvent = { seq: number; message: string }
/**
 * One phase of a workflow run, from a `workflows/wf_<id>.json` manifest.
 */
export type WorkflowPhase = { title: string; detail: string | null }
/**
 * A workflow run's manifest (`workflows/wf_<id>.json`), the data model behind the
 * `/workflows`-style view. Field names mirror the on-disk camelCase manifest. The
 * dynamic, per-entry-shaped `workflowProgress` and `result` are kept raw
 * ([`Value`]) — the Workflow display task types them.
 */
export type WorkflowRun = { runId: string; taskId: string | null; status: string | null; workflowName: string | null; defaultModel: string | null; durationMs: number | null; agentCount: number | null; totalTokens: number | null; totalToolCalls: number | null; summary: string | null; phases?: WorkflowPhase[]; 
/**
 * Array of `{type:"workflow_phase"|"workflow_agent", …}` entries — kept raw.
 */
workflowProgress?: JsonValue; 
/**
 * The workflow's final return value — kept raw.
 */
result?: JsonValue }
/**
 * Identity of one worktree of a repository (the cheap, always-listed part).
 * 
 * A repository has exactly one MAIN worktree (the original checkout) plus any
 * number of LINKED worktrees created with `git worktree add`. Each is a
 * separate working directory sharing the same `.git` history — which is what
 * lets several `claude` agents work the same repo in parallel without stepping
 * on each other.
 */
export type WorktreeInfo = { 
/**
 * Absolute path of the worktree's working directory.
 */
path: string; 
/**
 * Short branch name (`refs/heads/` stripped). `None` when detached or bare.
 */
branch: string | null; 
/**
 * Full HEAD commit oid. `None` for the bare entry.
 */
head: string | null; 
/**
 * The repository's MAIN worktree (the first entry `git` lists). The one
 * worktree that can never be removed.
 */
is_main: boolean; 
/**
 * HEAD is detached (no branch checked out).
 */
is_detached: boolean; 
/**
 * Locked via `git worktree lock` (a removal needs `--force`).
 */
is_locked: boolean; 
/**
 * The bare repository entry (has no working tree of its own).
 */
is_bare: boolean }
/**
 * Working-tree status of one worktree (the heavier, on-demand part — one extra
 * `git` call per worktree, so it is fetched lazily by the manager, never for
 * the always-on indicator).
 */
export type WorktreeStatus = { 
/**
 * At least one tracked file has staged or unstaged modifications.
 */
dirty: boolean; 
/**
 * At least one untracked file is present.
 */
untracked: boolean; 
/**
 * Number of entries `git status --porcelain` reports (changed + untracked).
 */
changed_files: number; 
/**
 * Commits ahead of the branch's upstream. `None` when no upstream is set.
 */
ahead: number | null; 
/**
 * Commits behind the branch's upstream. `None` when no upstream is set.
 */
behind: number | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
