// Stable IPC surface for the whole app.
// Features import { commands, events } from here, never from ./bindings (raw,
// generated) nor ./provider (the real/mock switch). Types come straight from the
// generated bindings so they always track the Rust contract.

export { commands, events, isTauri } from "./provider";

export type {
  AgentInfo,
  BackgroundTask,
  BackgroundTaskKind,
  BackgroundTaskStatus,
  BranchInfo,
  CommitFile,
  CommitInfo,
  ConversationItem,
  ConversationRecord,
  DiskConversation,
  ExtScope,
  ExtensionsSnapshot,
  FileContent,
  ForkOutcome,
  FsChangeEvent,
  FsEntry,
  FsWatchErrorEvent,
  GitDiff,
  GitFileEntry,
  GitStatus,
  ImageContent,
  JsonValue,
  MarketplaceInfo,
  McpAuthResult,
  McpServerInfo,
  McpServerLive,
  NormalizedBlock,
  PermissionDecision,
  PermissionMode,
  PermissionRequestPayload,
  PersistedState,
  PlanUsage,
  PluginContents,
  PluginInfo,
  Pong,
  RemoteControlState,
  RepoRecord,
  Result,
  RewindOutcome,
  SearchHit,
  SessionCommandsEvent,
  SessionMessageEvent,
  SessionPermissionEvent,
  SessionRemoteControlEvent,
  SessionStateEvent,
  SessionStatePayload,
  SessionTaskEvent,
  SessionTitleEvent,
  SessionSummaryEvent,
  SkillInfo,
  SlashCommand,
  TickEvent,
  UsageError,
  UsageWindow,
  WorkflowJournal,
  WorkflowPhase,
  WorkflowRun,
  WorktreeInfo,
  WorktreeStatus,
} from "./bindings";
